[project]
name = "EnvSync"
version = "0.1.0"
description = "Windows环境变量实时刷新工具"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["pywin32>=306"]

[tool.uv]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[project.optional-dependencies]
dev = ["pyinstaller>=6.0"]
